### ISSUE TITLE
BatchNorm implementation for RealNVP

### ISSUE THREAD

**Issue by vinsis** [kamenbliznashki/normalizing_flows#12]
In [these lines](https://github.com/kamenbliznashki/normalizing_flows/blob/master/maf.py#L177-L178) you are calculating the mean and variance for the entire batch. I believe means and variances should be calculated for each channel like so:

```python
self.batch_mean = x.mean([0,2,3])
self.batch_var = x.var([0,2,3]) 
```

unless you reshape the tensor before passing to the batchnorm layer.

Can you please take a look and see if it's a bug?

**Comment by kamenbliznashki** [comment]
Hi - this is a 1d implementation following the MAF paper and experiments, where the authors used tabular datasets.

**Comment by vinsis** [comment]
Got it, thanks
