### ISSUE TITLE
Just curious, why do you also have an ActNorm layer in the coupling Layer ?

### ISSUE THREAD

**Issue by rmehta1987** [kamenbliznashki/normalizing_flows#3]
I haven't run comparison with original code, but does have actNorm layer in the coupling layer improve performance ?

https://github.com/kamenbliznashki/normalizing_flows/blob/71e630ced23c33ff34db841da3423a6f18bee5bf/glow.py#L196

**Comment by kamenbliznashki** [comment]
The original implementation includes an actnorm after all but the final conv in the coupling layer. (see ([here](https://github.com/openai/glow/blob/eaff2177693a5d84a1cf8ae19e8e0441715b82f8/tfops.py#L236) the code used in the intermediate convs of the coupling layer). I didn't run this with and without actnorm inside the coupling layer, but my guess is given the depth of the flow and batch size at larger resolutions, normalizing preactivations everywhere helped stability.
