### ISSUE TITLE
 name 'optimizer_state' is not defined

### ISSUE THREAD

**Issue by manyfeatures** [kamenbliznashki/normalizing_flows#5]
When I launch `python planar_flow.py --train --target_potential=u_z1 --flow_length=2`
I get an error 
```
Traceback (most recent call last):
  File "planar_flow.py", line 291, in <module>
    if optimizer_state: optimizer.load_state_dict(optimizer_state)
NameError: name 'optimizer_state' is not defined
```

**Comment by kamenbliznashki** [comment]
Optimizer state only needs to be loaded if we're restoring from a checkpoint. Thanks for pointing this out. I just committed a fix.
