### ISSUE TITLE
Deprecated usage of torch.uint8 in BNAF

### ISSUE THREAD

**Issue by Svito-zar** [kamenbliznashki/normalizing_flows#9]
When trying to run `bnaf.py` I am getting the following warning:
`Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at /opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/ATen/native/IndexingUtils.h:20)`

After searching for solutions I found a Github [issue](https://github.com/pytorch/pytorch/issues/29365) and Stackoverflow [post](https://stackoverflow.com/questions/60067164/tracing-back-deprecated-warning-in-pytorch) related to it.

My assumption is that it is related to the way datasets are being constructed.

**Comment by kamenbliznashki** [comment]
This is due to a change in pytorch -- version 1.2 deprecated uint8 masks for bool. You can fix this in bnaf.py line 190: `logdet[self.mask_d.byte()]` should be `logdet[self.mask_d.bool()]`

**Comment by Svito-zar** [comment]
Thank you for your help, @kamenbliznashki
